---
resources:
- name: attendee-service-source
  type: git
  source:
    uri: https://kstrini:02a49e0189bb6600da929bde5b336529aa39b961@github.com'/kstrini/pcf-attendee-service-code
    branch: concourse_deployment

- name: deploy-attendee-service
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: pcfdev-org
    space: pcfdev-space
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml

- name: deploy
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

- name: smoke_test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: <YOUR_ATTENDEE_SERVICE_URL>
